[package]
name = "serde_examples"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version="1.0.218",features=["derive"]}
serde_json = "1.0.140"
borsh = { version = "1.5", features = ["derive"]}
